services:
  - type: web
    name: trustus-bank-api
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TRUSTUS_JWT_SECRET
        generateValue: true
      - key: TRUSTUS_CORS_ALLOWED_ORIGIN_PATTERNS
        sync: false
